package thecudster.sre.util.sbutil;

public class DungeonChestUtils {
    public static final String[] notProfit = {
            "ENCHANTED_BOOK-INFINITE_QUIVER-6",
            "ENCHANTED_BOOK-FEATHER_FALLING-6",
            "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-1",
            "HOT_POTATO_BOOK",
            "SCARF_STUDIES",
            "ADAPTIVE_BOOTS",
            "ENCHANTED_BOOK-ULTIMATE_WISDOM-1",
            "ENCHANTED_BOOK-ULTIMATE_REND-1",
            "DARK_ORB",
            "GIANT_TOOTH",
            "PRECURSOR_GEAR",
            "BONZO_MASK",
            "PET-SPIRIT-LEGENDARY",
            "PET-SPIRIT-EPIC",
            "ENCHANTED_BOOK-OVERLOAD-1",
            "RED_NOSE",
            "BONZO_STAFF",
            "STONE_BLADE",
            "ADAPTIVE_CHESTPLATE",
            "SPIRIT_BONE",
            "THORN_BOOTS",
            "GOLEM_POPPY",
            "FUMING_POTATO_BOOK",
            "SPIRIT_BOW",
            "WITHER_CLOAK",
            "WITHER_CATALYST",
            "WITHER_LEGGINGS",
            "WITHER_HELMET",
            "NECROMANCER_LORD_BOOTS",
            "NECROMANCER_LORD_LEGGINGS",
            "NECROMANCER_LORD_HELMET",
            "NECROMANCER_SWORD",
            "SUMMONING_RING",
            "SHADOW_ASSASSIN_BOOTS",
            "SHADOW_ASSASSIN_LEGGINGS",
            "SHADOW_ASSASSIN_HELMET",
            "SHADOW_FURY",
            "LIVID_DAGGER",
            "AOTE_STONE"
    };
    public static final String[] sellable = {
            "TRAINING_WEIGHTS",
            "POTION",
            "SPIRIT_LEAP",
            "DUNGEON_LORE_PAPER",
            "ENCHANTED_ROTTEN_FLESH",
            "ENCHANTED_BONE",
            "ENCHANTED_BOOK-ULTIMATE_BANK-1",
            "ENCHANTED_BOOK-ULTIMATE_NO_PAIN_NO_GAIN-1",
            "ENCHANTED_BOOK-ULTIMATE_JERRY-1",
            "ENCHANTED_BOOK-INFINITE_QUIVER-6",
            "ENCHANTED_BOOK-FEATHER_FALLING-6"
    };
}
